config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "performances#index"

  resources :performances
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/performance.rb
class Performance < ApplicationRecord
  has_one_attached :video

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :update]
  before_action :load_performance, except: [:index, :new, :create]

  def index
    @performances = Performance.all
  end

  def new
    @performance = Performance.new
  end

  def create
    @performance = Performance.new(performance_params)

    if @performance.save
      render :json => { :success => true }
    else
      render :new
    end
  end


  def update
    if @performance.update(performance_params)
      render :json => { :success => true }
    else
      render :edit
    end
  end

  def destroy
    @performance_id = params[:id]
    @performance.destroy

    respond_to do |format|
      format.html { redirect_to performances_path }
      format.js { render :destroy }
    end
  end

  private

  def load_performance
    @performance = Performance.find(params[:id])
  end

  def performance_params
    params.require(:performance).permit(:title, :video, :audio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
  def formatted_date(created_at)
    if created_at < 1.week.ago
      created_at.strftime("%b %d, %Y")
    else
      time_ago_in_words(created_at) + " ago"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerformancePortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class='<%= "#{controller_name} #{action_name}" %>'>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/performances/destroy.js.erb
document.getElementById("performance-<%= @performance_id %>").remove();

app/views/performances/edit.html.erb
<h1>Edit Performance</h1>

<%= render partial: 'performances/partials/performance_form' %>

app/views/performances/index.html.erb
<h1>
  Your Performances 
  <%= link_to new_performance_path, class: 'clear-link ml2' do %>
    <%= image_tag 'plus.svg', class: 'd-flex' %>
  <% end %>
</h1>

<div class="list">
  <% @performances.each do |performance| %>
    <div class="item performance" id="performance-<%=performance.id%>">
      <div class="performance-thumbnail">
        <%- thumbnail = performance&.video&.preview(resize_to_limit: [150, 84.38])&.processed %>
        <%= image_tag url_for(thumbnail) if thumbnail %>        
      </div>

      <div class="performance-details">
        <h2>
          <%= performance.title %>
        </h2>

        <p>
          <%= formatted_date(performance.created_at) %>
        </p>
      </div>
      
      <div class="performance-actions">
        <%= link_to performance_path(performance), class: 'clear-link' do %>
          <%= image_tag 'play.svg' %>
        <% end %>

        <%= link_to edit_performance_path(performance), class: 'clear-link' do %>
          <%= image_tag 'edit.svg' %>
        <% end %>

        <%= link_to performance, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'clear-link' do %>
          <%= image_tag 'delete.svg' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/performances/new.html.erb
<h1>Record New Performance</h1>

<%= render partial: 'performances/partials/performance_form' %>

app/views/performances/partials/_performance_form.html.erb
<%= form_with(model: @performance, url: performances_path, local: true, html: { id: 'performance_form', data: { id: @performance.id } }) do |form| %>
  <%= form.text_field :title, id: 'performance_title', class: 'form-control', required: true, placeholder: 'Enter performance name' %>

  <div class="video-container">
    <video id="video_preview" autoplay muted></video>
  </div>

  <div class="buttons-group">
    <%= button_tag 'Record Video Selfie', type: 'button', id: 'record_button', class: 'btn btn-primary recording-button', disabled: false %>
    <%= button_tag 'Record Screen', type: 'button', id: 'record_screen_button', class: 'btn btn-primary recording-button', disabled: false %>
    <%= button_tag 'Stop', type: 'button', id: 'stop_button', class: 'btn btn-primary', disabled: false %>
    <%= form.submit 'Save', id: 'save_button', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/performances/show.html.erb
<h1 class="title">
  <%= @performance.title%>

  <%= link_to edit_performance_path(@performance), class: 'clear-link ml2' do %>
    <%= image_tag 'edit.svg' %>
  <% end %>

  <%= link_to @performance, method: :delete, data: { confirm: 'Are you sure?' }, class: 'clear-link ml2' do %>
    <%= image_tag 'delete.svg' %>
  <% end %>
</h1>

<p class="date"><%= formatted_date(@performance.updated_at) %></p>

<video class="video-player" controls>
  <source src=<%= rails_blob_path(@performance.video) %> type="video/webm"/>
</video>